#!/usr/bin/env bash
# reset_dns.sh
# 作用：彻底关闭本地 DNS（systemd-resolved / 127.0.0.53）
#       重建为用户自定义 DNS，并进行验证
# 适用：Ubuntu / Debian / CentOS / Alma / Rocky / Fedora / VPS 通用

set -e

TIMESTAMP=$(date +%Y%m%d-%H%M%S)
BACKUP_DIR="/root/dns-reset-backup-$TIMESTAMP"
mkdir -p "$BACKUP_DIR"

echo "📦 备份目录：$BACKUP_DIR"

# ----------------------------
# 1. 读取用户 DNS
# ----------------------------
if [ "$#" -gt 0 ]; then
  DNS_SERVERS=("$@")
else
  read -rp "请输入新的 DNS（空格分隔，如 1.1.1.1 8.8.8.8）： " -a DNS_SERVERS
fi

if [ "${#DNS_SERVERS[@]}" -eq 0 ]; then
  echo "❌ 未输入 DNS，退出"
  exit 1
fi

echo "✅ 新 DNS：${DNS_SERVERS[*]}"
sleep 1

# ----------------------------
# 2. 彻底关闭 systemd-resolved
# ----------------------------
if systemctl list-unit-files | grep -q systemd-resolved; then
  echo "🛑 关闭 systemd-resolved..."
  systemctl stop systemd-resolved || true
  systemctl disable systemd-resolved || true

  cp -a /etc/systemd/resolved.conf "$BACKUP_DIR/" 2>/dev/null || true
fi

# ----------------------------
# 3. 解除 resolv.conf 软链接
# ----------------------------
if [ -L /etc/resolv.conf ]; then
  echo "🔗 解除 /etc/resolv.conf 软链接"
  cp -a /etc/resolv.conf "$BACKUP_DIR/resolv.conf.link.bak"
  rm -f /etc/resolv.conf
fi

# ----------------------------
# 4. 关闭 NetworkManager 自动 DNS
# ----------------------------
if command -v nmcli >/dev/null 2>&1; then
  echo "🛑 禁止 NetworkManager 自动控制 DNS"
  NM_CONN=$(nmcli -t -f NAME c show --active | head -n1)
  if [ -n "$NM_CONN" ]; then
    nmcli c modify "$NM_CONN" ipv4.ignore-auto-dns yes || true
    nmcli c modify "$NM_CONN" ipv6.ignore-auto-dns yes || true
    nmcli c up "$NM_CONN" || true
  fi
fi

# ----------------------------
# 5. 写入全新的 resolv.conf
# ----------------------------
echo "✍️ 重建 /etc/resolv.conf"
cat > /etc/resolv.conf <<EOF
# Generated by reset_dns.sh at $TIMESTAMP
$(for d in "${DNS_SERVERS[@]}"; do echo "nameserver $d"; done)
options timeout:2 attempts:2 rotate
EOF

chmod 644 /etc/resolv.conf

# ----------------------------
# 6. DNS 生效验证
# ----------------------------
echo "🔍 开始 DNS 验证..."
echo ""

TEST_DOMAIN="example.com"

if command -v dig >/dev/null 2>&1; then
  TOOL="dig"
elif command -v nslookup >/dev/null 2>&1; then
  TOOL="nslookup"
elif command -v host >/dev/null 2>&1; then
  TOOL="host"
else
  TOOL="none"
fi

for dns in "${DNS_SERVERS[@]}"; do
  echo "➡️ 测试 DNS：$dns"

  case "$TOOL" in
    dig)
      dig @"$dns" "$TEST_DOMAIN" +time=2 +tries=1 +short && echo "✅ 成功" || echo "❌ 失败"
      ;;
    nslookup)
      nslookup "$TEST_DOMAIN" "$dns" && echo "✅ 成功" || echo "❌ 失败"
      ;;
    host)
      host "$TEST_DOMAIN" "$dns" && echo "✅ 成功" || echo "❌ 失败"
      ;;
    *)
      echo "⚠️ 未安装 dig/nslookup/host，跳过单独 DNS 验证"
      getent ahosts "$TEST_DOMAIN" && echo "✅ 系统解析正常" || echo "❌ 系统解析失败"
      ;;
  esac

  echo ""
done

# ----------------------------
# 7. 当前系统 DNS 状态
# ----------------------------
echo "📡 当前生效的 /etc/resolv.conf："
cat /etc/resolv.conf

echo ""
echo "✅ DNS 彻底重置完成！"
echo "📂 备份目录：$BACKUP_DIR"

echo ""
echo "🔁 如需回滚："
echo "sudo cp -a $BACKUP_DIR/resolv.conf.link.bak /etc/resolv.conf"
